test/connect-mongo.test.js

this test just compare if the expires date are changed after run .touch()

adding test to validate the .touch() method

---

lib/connect-mongo.js

I had problems with callbacks getting invoked multiple times when an error happens.

Short circuiting when callback(err)

---

lib/connect-mongo.js

Fixes #172.
I'm not sure how I should go about adding a test for this.

Use duck typing heuristics for detecting native Db object

---

lib/connect-mongo.js

Had to close the previous issue after a merge madness

Exposing timer as self.timer. Added timer.unref()

---

src/index.js
test/connect-mongo.test.js

add support for promises with options.dbPromise

---

src/index.js

fix(collectionReady): fix bluebird warning

---

README.md

Self explanatory, matching syntax up for MongoStore.

Fixed capitalization in Lazy session update [ci skip]

---

src/index.js

I find it useful
Maybe it should be done for all emit events to keep the same signature (event, sid, session)?

Pass session too in the event

---

CHANGELOG.md
README.md
package.json
src/index.js
test/events.js

This is an improvement on @KSH-code's PR #301.
It fixes warnings about non-atomic operations, bug #300.

Update deprecated methods

---

src/index.js

Fix interval autoremove mode to use current date with every interval

---

src/index.js
test/legacy-tests.js

Support for the optional store.all function of the express-session storage.

Implementation of store.all function

---

README.md
src/crypto.js
src/index.js
test/crypto.js
test/events.js

The following functionality is included:
- Symmetric encryption of session data following OWASP recommendations.
- Updates to readme providing crypto options
- Key derivation to strengthen provided secret in accordance with NIST SP 800-108 & 800-56c
- Unique IV conforming to RFC 4309 & NIST SP 800-38d
- Support for varying symmetric algorithms, key, iv & authentication tag sizes, hashing algorithms & ciphertext encoding
- Test harness for crypto class as well as using transparent crypto functionality

Transparent crypto support

---

CHANGELOG.md
README.md
package.json

docs: update readme and bump version to 3.0.0

---

src/helper.js
src/index.js
test/helper.test.js
test/legacy-tests.test.js

feat: add useUnifiedTopology=true and refactor merge config logic

---

package.json
src/types.d.ts

chore: add typescript types. fixes #338

---

package.json
src/types.d.ts
yarn.lock

@types/express updated to 4.17.9
@types/express-session updated to 1.17.3
Resolves #373

fix: import definition for SessionData from @types/express-session

---

CHANGELOG.md
package.json
src/lib/MongoStore.spec.ts
src/lib/MongoStore.ts
src/test/integration.spec.ts
yarn.lock

fix: crypto decode implementation

---

example/mongoose-multiple-connections.js

- Documentation: added example for multiple mongoose connections
- No example available for dealing with multiple mongoose connections
- #403

docs(example): added an example for multiple mongoose connections

---

CHANGELOG.md
src/lib/MongoStore.spec.ts
src/lib/MongoStore.ts

fix: all() not work with crypto enabled

---

MIGRATION_V4.md

- docs update
- the example is incorrect

docs: migration guide argument correction
