- Readme.md
- lib/connect-mongo.js
- test/connect-mongo.test.js
- test/mocha.opts
The purpose of this feature is improve the performance of updates on database by limiting the number of updates that are made in a period of time.
Exemple:
1) users can refresh the page 5 times repeatedly due to a slow internet connection, and this will make 5 updates on database.
2) users can navigate in 50 pages in less than 10 minutes and this will make 50 updates on database.
Note: the tests are taking 3 seconds to run due to an async test of this feature.
> adding the touchAfter feature to allow lazy updates on database

- lib/connect-mongo.js
I just realized that I was accidentally setting the `lastModified` prop at the session object, this commit solve this mistake.
> removing the lastModified prop from the session object before update

- lib/connect-mongo.js
Db.open() doesn't run callback in my case.
UPD: I am not right. The problem appears even in native driver @ 1.x, when my connection string is `mongodb://127.0.0.1:27017/users`
```
connect-mongo switched to state: init +0ms
connect-mongo use strategy: `native_db` +1ms
connect-mongo switched to state: connected +1ms
connect-mongo switched to state: connecting +0ms
```
UPD: In Mongo@2.x driver db.openCalled is undefined and db.open(callback) doesn't fire callback at all, so we can act like the connection is already established. Therefore fix by @barisusakli works nice with this PR: https://github.com/kcbanner/connect-mongo/issues/161#issuecomment-79466714
> Fix native driver events order

- lib/connect-mongo.js
mongodb@2.x doesn't have openCalled property, and it's okay not to call db.open() directly.
https://github.com/kcbanner/connect-mongo/issues/161#issuecomment-88224772
`make test` runs okay on my local computer
Failing test is really weird
> [WIP] Respect missing openCalled property in mongodb@2.x

- src/index.js
Scenario: When running unit tests via Gulp that leverage MongoStore/connect-mongo, the lingering this.db instance remains open, preventing the node process from terminating. 
Workaround: Users have to currently manually reach inside the MongoStore and call instance.db.close(). 
This pull request adds a simple .close() operation that allows for manual disposal of the MongoStore.
> Added .close operation to MongoStore.

- src/index.js
Still receiving this error after 1.3.2.
TypeError: Cannot read property 'upserted' of undefined
at /root/app/node_modules/connect-mongo/src/index.js:251:36
at tryCatcher (/root/app/node_modules/connect-mongo/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/root/app/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:504:31)
at Promise._settlePromise (/root/app/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:561:18)
at Promise._settlePromise0 (/root/app/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:606:10)
at Promise._settlePromises (/root/app/node_modules/connect-mongo/node_modules/bluebird/js/release/promise.js:685:18)
at Promise._fulfill …
> Update to #228

- src/index.js
`sessionStore.on('touch', ...)` gets called on every requests currently (with `touchAfter` option enabled), this change makes it work as expected (max one call every touchAfter periods)
only https://github.com/jdesboeufs/connect-mongo/blob/master/src/index.js#L294 should emit touch
> avoiding calling touch in get

- src/index.js
Have a look at mongodb [docs](https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/)
db.collection.ensureIndex(keys, options)  
Deprecated since version 3.0.0: db.collection.ensureIndex() is now an alias for db.collection.createIndex().
Creates an index on the specified field if the index does not already exist.
Use db.collection.createIndex() rather than db.collection.ensureIndex() to create new indexes.
> swap ensureIndex with createIndex fixes #268

- CHANGELOG.md
- README.md
- package.json
- src/index.js
- test/events.js
close #297 
close #300 
@jdesboeufs 
change remove and update to deleteOne and updateOne
> Fix: print DeprecationWarning

- .travis.yml
- README.md
- package.json
- src/index.js
- test/events.js
- test/legacy-tests.js
- yarn.lock
This PR aims to upgrade the `mongodb` and `mongoose` driver version to have support for newer version of MongoDB. First, take a look on the compatibility matrix:
https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility
https://mongoosejs.com/docs/compatibility.html
For my own use case (and maybe most of the user), I need to use MongoDB 3.6 which the current code base does not support. 
Due to the `mongodb` driver upgrade, the behavior of `client` and `db` is different in driver v2 and v3 so some part of the code must be rewritten. Note that we currently have 3 "connection strategy"
1. `options.url` & `options.mongoOptions` - remain the same
2. `options.mongooseConnection` - remain the same
3. `options.clientPromise` - this is the new one
In …
> upgrade mongodb and mongoose driver version to support newer version of MongoDB

- README.md
- src/index.js
Useful for adjusting the write concern.
> Add option writeOperationOptions: options object to pass to every MongoDB write operation call that supports it (e.g. update, remove)

- src/index.js
The patch checks if the client is connected, and if not, registers an event listener for the open event.  Once the event fires, the new connection proceeds as normal.
If a non-connected client is passed in currently, it will fail with the following error:
```
MongoError: MongoClient must be connected before calling MongoClient.prototype.db
```
This works with the native MongoDB driver, and follows a similar pattern to the existing handling of Mongoose connections.
> Wait for client open, before calling db.

- src/types.d.ts
This option is already supported in the code and documented in:
https://github.com/jdesboeufs/connect-mongo#crypto-options
> fix: add missing `secret` option to TS definition

- README.md
- src/index.js
- test/options.test.js
This PR is a result of discussion #335 in which a couple of methods for specifying which database to use were suggested:
1. Adding database *name* option which can be passed to `client.db()`
2. Adding database *instance* option which can be used without needing to invoke `client.db()`
This PR implemented 1, because the codebase seemed to be built in light of `client`, e.g. `MongoStore.close()` won't be invoked when database instance is used, and I wanted to add as little code as possible.
And this PR will also update `README.md` to add example usage for `dbName` option and to incorporate all available options into Options section.
> feat: add dbName option

- src/types.d.ts
Added the `dbName` option type added in v3.2.0 in the typescript definition.
> Add dbName type to typescript definition

- README.md
The default authSource db should be `admin`,not `admins`
```
app.use(session({
store: new MongoStore({
url: 'mongodb://user12345:foobar@localhost/test-app?authSource=admin&w=1',
mongoOptions: advancedOptions // See below for details
})
}));
```
> The default authSource db should be `admin`,not `admins`

- src/lib/MongoStore.ts
Typo fix.
The assert message direct to provide `mongoUr` instead of `mongoUrl`.
> chore: fix typo in assert message

- CHANGELOG.md
- package.json
- src/lib/MongoStore.ts
- yarn.lock
> fix: move writeConcern option away from top-level to remove deprecation warning #422

- .github/workflows/sanity.yml
- .nycrc.json
- CHANGELOG.md
- package.json
- src/lib/MongoStore.spec.ts
- src/lib/MongoStore.ts
- src/test/testHelper.ts
- yarn.lock
> fix: upgrade mongodb depns to V4

- CHANGELOG.md
- src/lib/MongoStore.ts
- yarn.lock
> fix: callback was already called when code throw after set function

- CHANGELOG.md
- package.json
- **What kind of change does this PR introduce?** Bug fix
- **What is the current behavior?** Allows installation on Node < 12
- **What is the new behavior (if this is a feature change)?** Requires Node >= 12.9 to install.
- **Other information**: This matches the engine required by the mongodb package;
see https://github.com/mongodb/node-mongodb-native/blob/4.1/package.json#L88
> fix: require engines newer than node 12.9

- CHANGELOG.md
- package.json
- src/lib/MongoStore.spec.ts
- src/lib/MongoStore.ts
- yarn.lock
* MongoDB 5.0 has been released for a while, this PR introduces a breaking change to upgrade the peer dependency `mongodb` to 5.0.0
https://github.com/jdesboeufs/connect-mongo/issues/465
I considered the changes in this PR as breaking changes since the `MongoClient` typing in mongodb@5 is not compatible with the one in mongodb@4, so the upgrade will break the interface.
> Upgrade mongodb to 5.0.0

- .github/workflows/sanity.yml
- CHANGELOG.md
- README.md
- package.json
- yarn.lock
Updates the `mongodb` dependency from v5.0.0 to v6.0.0.
I didn't see anything in the [release notes](https://github.com/mongodb/node-mongodb-native/blob/HEAD/etc/notes/CHANGES_6.0.0.md) to warrant changes to the code, so this PR just updates the MongoDB and Node versions, following the PR for v5.
- [n/a] Added test cases
> chore: extend mongodb compatibility to 6.x
